name: Deploy HTML Page

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version if needed

      - name: Install dependencies
        run: npm install # Run this if you have a package.json, otherwise skip this step

      - name: Create HTML with secret
        run: |
          # Replace the placeholder in your HTML with the secret URL
          sed -i 's|<YOUR_PLACEHOLDER_FOR_URL>|${{ secrets.EXCEL_FILE_URL }}|g' path/to/your.html
