name: Deploy HTML Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -R

      - name: Show HTML file before modification
        run: cat index.html

      - name: Create HTML with secret
        run: |
          sed -i 's|<EXCEL_FILE_URL>|${{ secrets.EXCEL_FILE_URL }}|g' index.html

      - name: Show HTML file after modification
        run: cat index.html
