name: Deploy HTML Page

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '20'  # Specify Node.js version 20

      - name: Create HTML with secret
        run: |
          sed -i 's|<EXCEL_FILE_URL>|${{ secrets.EXCEL_FILE_URL }}|g' index.html
